<?php

declare(strict_types=1);

namespace App\Enums;

enum ChargeKind: string
{
    /** Extra scope agreed during the project — "three more pages". */
    case Extra = 'extra';

    /** A revision beyond what the original scope included. */
    case Revision = 'revision';

    /** One-off maintenance or support work after delivery. */
    case Maintenance = 'maintenance';

    /** One month of a recurring retainer, generated automatically. */
    case RetainerCycle = 'retainer_cycle';

    public function label(): string
    {
        return match ($this) {
            self::Extra => 'Extra scope',
            self::Revision => 'Paid revision',
            self::Maintenance => 'Maintenance',
            self::RetainerCycle => 'Retainer',
        };
    }

    /** Generated by the scheduler rather than entered by a person. */
    public function isAutomatic(): bool
    {
        return $this === self::RetainerCycle;
    }
}
